app/urls.py
from django.urls import path
from .views.tarefa_views import *
from .views.usuario_views import *
urlpatterns = [
    path('', listar_tarefas, name = 'listar_tarefas'),
    path('cadastrar_tarefas/', cadastrar_tarefa, name = 'cadastrar_tarefas'),
    path('editar_tarefa/<int:id>', editar_tarefa, name = 'editar_tarefa'),
    path('remover_tarefa/<int:id>', remover_tarefa, name = 'remover_tarefa'),
    path('cadastrar_usuario/', cadastrar_usuario, name = 'cadastrar_usuario'),
    path('logar_usuario/', logar_usuario, name = 'logar_usuario'),
    path('deslogar_usuario/', deslogar_usuario, name = 'deslogar_usuario'),
]

treinaweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

app/models.py
from django.db import models
from django.contrib.auth.models import User

class Tarefa(models.Model):
    PRIORIDADE_CHOICES = [
        ('A', 'Alta'),
        ('N', 'Normal'),
        ('B', 'Baixa'),
    ]
    titulo = models.CharField(max_length=30, null=False, blank=False)
    descricao = models.CharField(max_length=100, null=False, blank=False)
    data_expiracao = models.DateField(null=False, blank=False)
    prioridade = models.CharField(max_length=1, choices=PRIORIDADE_CHOICES,null=False, blank=False)
    usuario = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

app/forms.py
from django import  forms
from .models import Tarefa
class TarefaForm( forms.ModelForm):
    class Meta:
        model = Tarefa
        exclude = ('usuario', )
        fields = '__all__'

app/views.py
from django.shortcuts import render, redirect
from .forms import TarefaForm
from .entidades.tarefa import Tarefa
from .services import tarefa_service
def listar_tarefas(request):
    tarefas = tarefa_service.listar_tarefas()
    return render(request, 'tarefas/listar_tarefas.html',{'tarefas': tarefas})

def cadastrar_tarefa(request):
    if request.method == 'POST':
        form_tarefa = TarefaForm(request.POST)
        if form_tarefa.is_valid():
            titulo = form_tarefa.cleaned_data['titulo']
            descricao = form_tarefa.cleaned_data['descricao']
            data_expiracao = form_tarefa.cleaned_data['data_expiracao']
            prioridade = form_tarefa.cleaned_data['prioridade']
            tarefa_nova = Tarefa(titulo = titulo, descricao=descricao,data_expiracao= data_expiracao,
                                 prioridade= prioridade)
            tarefa_service.cadastrar_tarefa(tarefa_nova)
            return redirect('listar_tarefas')
    else:
        form_tarefa = TarefaForm()
    return render(request, 'tarefas/form_tarefa.html',{'form_tarefa': form_tarefa})

def editar_tarefa(request, id):
    tarefa_db = tarefa_service.listar_tarefas_id(id)
    form_tarefa = TarefaForm(request.POST or None, instance=tarefa_db)
    if form_tarefa.is_valid():
        titulo = form_tarefa.cleaned_data['titulo']
        descricao = form_tarefa.cleaned_data['descricao']
        data_expiracao = form_tarefa.cleaned_data['data_expiracao']
        prioridade = form_tarefa.cleaned_data['prioridade']
        tarefa_nova = Tarefa(titulo=titulo, descricao=descricao, data_expiracao=data_expiracao,
                             prioridade=prioridade)
        tarefa_service.editar_tarefa(tarefa_db, tarefa_nova)
        return redirect('listar_tarefas')
    return render(request, 'tarefas/form_tarefa.html', {'form_tarefa': form_tarefa})

def remover_tarefa(request, id):
    tarefa_db = tarefa_service.listar_tarefas_id(id)
    if request.method == 'POST':
        tarefa_service.deletar_tarefa(tarefa_db)
        return redirect('listar_tarefas')
    return render(request, 'tarefas/confirma_exclusao.html', {'tarefa': tarefa_db})

app/views/tarefa_views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from ..forms import TarefaForm
from ..entidades.tarefa import Tarefa
from ..services import tarefa_service

@login_required()
def listar_tarefas(request):
    tarefas = tarefa_service.listar_tarefas(request.user)
    return render(request, 'tarefas/listar_tarefas.html', {'tarefas': tarefas})
@login_required()
def cadastrar_tarefa(request):
    if request.method == 'POST':
        form_tarefa = TarefaForm(request.POST)
        if form_tarefa.is_valid():
            titulo = form_tarefa.cleaned_data['titulo']
            descricao = form_tarefa.cleaned_data['descricao']
            data_expiracao = form_tarefa.cleaned_data['data_expiracao']
            prioridade = form_tarefa.cleaned_data['prioridade']
            tarefa_nova = Tarefa(titulo = titulo, descricao=descricao,data_expiracao= data_expiracao,
                                 prioridade= prioridade, usuario=request.user)
            tarefa_service.cadastrar_tarefa(tarefa_nova)
            return redirect('listar_tarefas')
    else:
        form_tarefa = TarefaForm()
    return render(request, 'tarefas/form_tarefa.html', {'form_tarefa': form_tarefa})
@login_required()
def editar_tarefa(request, id):
    tarefa_db = tarefa_service.listar_tarefas_id(id)
    if tarefa_db.usuario != request.user:
        return HttpResponse('Não permitido')
    form_tarefa = TarefaForm(request.POST or None, instance=tarefa_db)
    if form_tarefa.is_valid():
        titulo = form_tarefa.cleaned_data['titulo']
        descricao = form_tarefa.cleaned_data['descricao']
        data_expiracao = form_tarefa.cleaned_data['data_expiracao']
        prioridade = form_tarefa.cleaned_data['prioridade']
        tarefa_nova = Tarefa(titulo=titulo, descricao=descricao, data_expiracao=data_expiracao,
                             prioridade=prioridade, usuario=request.user)
        tarefa_service.editar_tarefa(tarefa_db, tarefa_nova)
        return redirect('listar_tarefas')
    return render(request, 'tarefas/form_tarefa.html', {'form_tarefa': form_tarefa})
@login_required()
def remover_tarefa(request, id):
    tarefa_db = tarefa_service.listar_tarefas_id(id)
    if tarefa_db.usuario != request.user:
        return HttpResponse('Não permitido')
    if request.method == 'POST':
        tarefa_service.deletar_tarefa(tarefa_db)
        return redirect('listar_tarefas')
    return render(request, 'tarefas/confirma_exclusao.html', {'tarefa': tarefa_db})

app/views/usuario_views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

@login_required()
def cadastrar_usuario(request):
    if request.method == 'POST':
        form_usuario = UserCreationForm(request.POST)
        if form_usuario.is_valid():
            form_usuario.save()
            return redirect('listar_tarefas')
    else:
        form_usuario = UserCreationForm()
    return render(request,'usuarios/form_usuario.html', {'form_usuario': form_usuario})



def logar_usuario(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        usuario = authenticate(request, username=username,password=password)
        if usuario is not None:
            login(request, usuario)
            return redirect('listar_tarefas')
        else:
            messages.error(request, 'As credenciais do usuario estão incorretas')
            return redirect('logar_usuario')
    else:
        form_login = AuthenticationForm()
    return render(request,'usuarios/login.html',{'form_login': form_login})

def deslogar_usuario(request):
    logout(request)
    return redirect('logar_usuario')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Listas tarefas</title>
    <link rel="stylesheet" href="{% static 'app/css/bootstrap.min.css' %}">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Gerenciador de tarefas</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'listar_tarefas' %}">Listar Tarefas <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'deslogar_usuario' %}">Logout <span class="sr-only">(current)</span></a>
      </li>
    </ul>

  </div>
</nav>
<main class="container">
{% block conteudo %}
 {% endblock %}

</main>
</body>
</html>

templates/tarefas/confirma_exclusao.html
{% extends 'base.html' %}

{% block conteudo %}

        <div class="card-mb3">
        <div class="card-header">
            Tem certeza que deseja remover?
        </div>
        <a class="card-body">
            <h5 class="card-title"> {{ tarefa.titulo }}</h5>
            <p class="card-text" >{{ tarefa.descricao }}</p>
            <hr>
            <form method="post">
                {% csrf_token %}
                <button class="btn btn-danger" type="submit">Remover</button>
            </form>
        </div>

{% endblock conteudo %}

templates/tarefas/form_tarefa.html
{% extends 'base.html' %}
{% load filtros %}
{% block conteudo %}
<form method="post">
    {% csrf_token %}

    <div class="form-group">
        {{ form_tarefa.titulo.errors }}
        <label>Titulo:</label>
        {{ form_tarefa.titulo|addclass:'form-control'}}
    </div>
    <div class="form-group">
        {{ form_tarefa.descricao.errors }}
        <label>Descrição:</label>
        {{ form_tarefa.descricao|addclass:'form-control' }}
    </div>
        <div class="form-group">
            {{ form_tarefa.data_expiracao.errors }}
        <label>Data de expiração:</label>
        {{ form_tarefa.data_expiracao|addclass:'form-control' }}
    </div>
    <div class="form-group">
        {{ form_tarefa.prioridade.errors }}
        <label>Prioridade:</label>
        {{ form_tarefa.prioridade|addclass:'form-control' }}
    </div>
    <div class="form-group">
        <input type="submit" value="Salvar">
    </div>
</form>
{% endblock conteudo %}

templates/tarefas/listar_tarefas.html
{% extends 'base.html' %}
{% load static %}
{% block conteudo %}
    {% for tarefa in tarefas %}
        <div class="card-mb3">
        <div class="card-header">
            {{ tarefa.get_prioridade_display }}
        </div>
        <a class="card-body">
            <h5 class="card-title"> {{ tarefa.titulo }}</h5>
            <p class="card-text" >{{ tarefa.descricao }}</p>
            <hr>
            <a href="{% url 'editar_tarefa' tarefa.id %}"> Editar Tarefa </a>
            <a href="{% url 'remover_tarefa' tarefa.id %}"> Remover Tarefa </a>
        </div>

        </div>

    {% endfor %}
    <a href="{% url 'cadastrar_tarefas' %}"><input type="button" class="btn btn-primary mb-3" value="cadastrar nova"> </a>
{% endblock conteudo %}

templates/usuarios/form_usuario.html
{% extends 'base.html' %}
{% load filtros %}
{% block conteudo %}
<form method="post">
{% csrf_token %}
    <div class="form-group">
        {{ form_usuario.username.errors }}
        <label>Nome de Usuario:</label>
        {{ form_usuario.username|addclass:'form-control' }}
    </div>
    <div class="form-group">
        {{ form_usuario.password1.errors }}
        <label>Senha::</label>
        {{ form_usuario.password1|addclass:'form-control' }}
    </div>
    <div class="form-group">
        {{ form_usuario.password2.errors }}
        <label>Repita a senha:</label>
        {{ form_usuario.password2|addclass:'form-control' }}
    </div>
    <div class="form-group">
        <input type="submit" value="Cadadastrar" class="btn btn-primary">
    </div>

</form>
{% endblock conteudo %}

templates/usuarios/login.html
{% extends 'base.html' %}
{% load filtros %}
{% block conteudo %}
<form method="post">
{% csrf_token %}
    {% for message in messages %}
        <div class=" alert alert-danger">
            {{ message }}
        </div>
    {% endfor %}
    <div class="form-group">
        <label>Nome de usuario:</label>
        {{ form_login.username|addclass:'form-control' }}
    </div>
    <div class="form-group">
        <label>Senha:</label>
        {{ form_login.password|addclass:'form-control' }}
    </div>
    <div class="form-group">
        <input type="submit" value="logar" class="btn btn-primary">
    </div>


</form>

{% endblock conteudo %}